[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "getml-docs4"
keywords = []
authors = [
  { name = "Jan", email = "jan@getml.com" },
]

version = "0.0.1"

[tool.hatch.envs.default]
dependencies = [
  "getml",
  "mkdocs-gen-files",
  "mkdocstrings[python-legacy]>=0.18",
  "docstring-to-markdown",
  "mkdocs-material"
]
python = "3.11"