[project]
name = "getml-docs"
keywords = []
authors = [
  { name = "Awais", email = "awais@getml.com" },
  { name = "Jan", email = "jan@getml.com" }
]

version = "0.0.1"

[tool.hatch.envs.default]
dependencies = [
  "mkdocs",
  "mkdocs-gen-files",
  "mkdocstrings-python",
  "docstring-to-markdown",
  "mkdocs-material @ git+ssh://git@github.com/squidfunk/mkdocs-material-insiders.git@9.5.20-insiders-4.53.8"
]
python = "3.11"