[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "getml-docs"
keywords = []
authors = [
  { name = "Jan", email = "jan@getml.com" },
]

version = "0.0.1"

[tool.hatch.envs.default]
dependencies = [
  "ipykernel",
  "ipython",
  "pip-tools",
  "pytest",
  "pytest-cov",
  "ruff>=0.2.0",
  "ruff-lsp",
  "getml",
  "mkdocs-gen-files",
  "mkdocstrings[python-legacy]>=0.18",
  "docstring-to-markdown"
]
python = "3.11"

[tool.black]
target-version = ["py311"]
line-length = 88

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow for string literals in exceptions
  "EM",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["proper"]

[tool.isort]
profile = "black"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]