authors:
  alex:
    name: Alexander Uhlig
    description: CEO <br>Co-Founder
    avatar: https://avatars.githubusercontent.com/u/2765645
    url: https://github.com/alxn4
    new: this
  awais:
    name: Awais
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/47096947
    url: https://github.com/awaismirza92
  benjamin:
    name: Benjamin
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/5569510
    url: https://github.com/brainslush
  alexandros:
    name: Alexandros Ladas
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/5097913
    url: https://github.com/cyclux
  jan:
    name: Jan Meyer
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/20856376
    url: https://github.com/jan-meyer-1986
  jeremy:
    name: Jeremy Perez
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/9077849
    url: https://github.com/jimixxperez
  joachim:
    name: Joachim Rosenberger
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/5442389
    url: https://github.com/Jogala
  patrick:
    name: Patrick Urbanke
    description: Chief Engineer <br>Co-Founder
    avatar: https://avatars.githubusercontent.com/u/19538706
    url: https://github.com/liuzicheng1987
  soeren:
    name: Sören Nikolaus
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/31724172
    url: https://github.com/srnnkls
  tony:
    name: Tony Fischer
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/3052212
    url: https://github.com/tku137
  manuel:
    name: Manuel Bellersen
    description: Engineering
    avatar: https://avatars.githubusercontent.com/u/1561354
    url: https://github.com/Urfoex