site_name: GetML Documentation

plugins:
  - search
  - autorefs
  - gen-files:
        scripts:
        - gen_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            members: true
            show_source: true
            show_signature_annotations: true
            show_type_annotations: true
            options:
              members_order: source
              separate_signature: true
              filters: [ "!^_" ]
              docstring_options:
                ignore_init_summary: true
              merge_init_into_class: true
              show_signature_annotations: true
              signature_crossrefs: true
              extensions:
                - docs/plugins/griffe_doclinks.py
            import:
              - https://docs.python.org/3/objects.inv
            docstring_style: sphinx


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: material