# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: getML Developer Portal
site_url: https://dev.getml.com/
site_author: Code17 GmbH
site_description: >-
  ...

# Repository
repo_name: getml
# repo_url: https://github.com/getml/getml-community

# Copyright
copyright: Copyright &copy; 2024 – Code17 GmbH

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/brand/getml-light.svg
  logo_dark_mode: assets/brand/getml-dark.svg
  favicon: images/favicon.png
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.annotate
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant.prefetch
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    # - navigation.footer
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.preview # disable! enable on page basis
    # - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    # two color schemes: a light mode, which is just called default, and a dark mode, which is called slate
    # primary color is used for the header, the sidebar, text links and several other components (default: indigo)
    # accent color is used to denote elements that can be interacted with, e.g. hovered links, buttons and scrollbars (default: indigo)
    - media: "(prefers-color-scheme)"
      toggle:
        # icon: material/brightness-5
        icon: fontawesome-pro/solid/sun-2
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep purple
      toggle:
        # icon: material/brightness-2
        icon: fontawesome-pro/duotone/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        # icon: material/brightness-6
        icon: fontawesome-pro/duotone/sun-horizon
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - autorefs
  # - blog
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            filters: ["!^_"]
            heading_level: 1
            ignore_init_summary: true
            line_length: 60 # not working
            members_order: source
            merge_init_into_class: true
            modernize_annotations: true # mkdocstring  insider
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: false
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_submodules: false
            show_symbol_type_heading: false
            show_symbol_type_toc: true # mkdocstring insider
            signature_crossrefs: true # mkdocstring insider
            # unwrap_annotated: false
  - privacy:
      links_attr_map:
        target: _blank
  - redirects:
      redirect_maps:
        'enterprise.md': 'enterprise/benefits.md'
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - table-reader
  - tags
  - meta

  - mike:
      canonical_version: latest

# Additional configuration
extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
    enterprise: Enterprise feature
    beta: This feature is in beta
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/getml
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/getml/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@code17-gmbh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/code17-gmbh
  version:
    provider: mike

# Extensions
markdown_extensions:
  - abbr
  - md_in_html
  - def_list
  - attr_list
  - admonition
  - footnotes
  - pymdownx.betterem
  - pymdownx.blocks.html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - src/docs/assets/snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - src/overrides/.icons
  - material.extensions.preview: # not working as expected
      targets:
        include:
          - reference/*
          - user_guide/*


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  # - assets/stylesheets/getml.css - Use for custom styles. Is loaded in header by default in overrides/main.html

draft_docs: |
  *_.md
  *debug.md
  install/build.md
  enterprise/training-and-support.md
  enterprise/guided-evaluation.md
  home/support/support.md

not_in_nav: |
  *debug.md
  enterprise/trial/trial-download.md
  reference/pipeline/column.md
  reference/pipeline/feature.md
  reference/pipeline/metadata.md
  reference/pipeline/sql_string.md
  reference/pipeline/table.md
  assets/snippets/*

nav:
  - Home: index.md

  - User Guide:
    - user_guide/index.md
    - Quick start:
      - user_guide/quick_start/index.md
    - Walkthrough:
      - user_guide/walkthrough/index.md
    # - Remote access: home/installation/remote_access.md
    - Concepts:
      - user_guide/concepts/index.md
      - getML Suite: user_guide/concepts/getml_suite/index.md
      - Managing projects: user_guide/concepts/project_management/index.md
      - Importing data: user_guide/concepts/importing_data/index.md
      - Annotating data: user_guide/concepts/annotating_data/index.md
      - Data model: user_guide/concepts/data_model/index.md
      - Preprocessing: user_guide/concepts/preprocessing/index.md
      - Feature engineering: user_guide/concepts/feature_engineering/index.md
      - Predicting: user_guide/concepts/predicting/index.md
      - Hyperparameter optimization: user_guide/concepts/hyperopt/index.md
      - Deployment: user_guide/concepts/deployment/index.md

  - Install:
    - install/index.md
    - Platform:
      - Linux: install/packages/linux.md
      - Docker: install/packages/Docker.md
    - From source:
      - Install API: install/source/python-api.md
      - Build engine & API: install/source/build.md
    - Uninstall:
      - Any platform: install/uninstall.md
    - Archive:
      - Archive: install/packages/archive.md

  - Enterprise:
    - Benefits: enterprise/benefits.md
    - Book a Demo: enterprise/book-demo.md
    - Feature List: enterprise/feature-list.md
    - Trial Download: enterprise/request-trial.md
    - Training & Support (draft): enterprise/training-and-support.md
    - Guided Evaluation (draft): enterprise/guided-evaluation.md
    - DEBUG (draft): enterprise/debug.md


  - API Reference:
    - reference/index.md
    # - DEBUG (draft): reference/debug.md
    - Python API:
      - reference/index.md
      - getml.data:
        - reference/data/index.md
        - Container: reference/data/container.md
        - DataFrame: reference/data/data_frame.md
        - DataModel: reference/data/data_model.md
        - Placeholder: reference/data/placeholder.md
        - Roles: reference/data/roles_obj.md
        - StarSchema: reference/data/star_schema.md
        - Subset: reference/data/subset.md
        - TimeSeries: reference/data/time_series.md
        - View: reference/data/view.md
        - access: reference/data/access.md
        - columns: reference/data/columns.md
        - relationship: reference/data/relationship.md
        - roles: reference/data/roles.md
        - split: reference/data/split.md
        - time: reference/data/time.md
        - subroles: reference/data/subroles.md
      - getml.database: reference/database/database.md
      - getml.datasets: reference/datasets/datasets.md
      - getml.engine: reference/engine/engine.md
      - getml.hyperopt:
        - reference/hyperopt/index.md
        - Gaussian Process: reference/hyperopt/gaussian.md
        - Latin Hypercube: reference/hyperopt/latin.md
        - Random: reference/hyperopt/random.md
      - getml.feature_learning:
        - reference/feature_learning/index.md
        - FastProp: reference/feature_learning/fastprop.md
        - Fastboost: reference/feature_learning/fastboost.md
        - Multirel: reference/feature_learning/multirel.md
        - Relboost: reference/feature_learning/relboost.md
        - RelMT: reference/feature_learning/relmt.md
        - aggregations:
            - reference/feature_learning/aggregations/index.md
            - types: reference/feature_learning/aggregations/types.md
            - sets: reference/feature_learning/aggregations/sets.md
        - loss_functions: reference/feature_learning/loss_functions.md
      - getml.project:
        - reference/project/index.md
        - DataFrames: reference/project/data_frames.md
        - Hyperopts: reference/project/hyperopts.md
        - Pipelines: reference/project/pipelines.md
      - getml.preprocessors:
        - reference/preprocessors/index.md
      - getml.pipeline:
        - reference/pipeline/index.md
        - Pipeline: reference/pipeline/pipeline.md
        - Columns: reference/pipeline/columns.md
        # - Column: reference/pipeline/column.md
        - Tables: reference/pipeline/tables.md
        # - Table: reference/pipeline/table.md
        - Features: reference/pipeline/features.md
        # - Feature: reference/pipeline/feature.md
        - Plots: reference/pipeline/plots.md
        - Scores: reference/pipeline/scores_container.md
        - Score: reference/pipeline/score.md
        - SQLCode: reference/pipeline/sql_code.md
        # - SQLString: reference/pipeline/sql_string.md
        # - metadata: reference/pipeline/metadata.md
        - metrics: reference/pipeline/metrics.md
        - dialect: reference/pipeline/dialect.md
      - getml.predictors:
        - reference/predictors/index.md
        - ScaleGBMClassifier: reference/predictors/scale_gbm_classifier.md
        - ScaleGBMRegressor: reference/predictors/scale_gbm_regressor.md
        - LinearRegression: reference/predictors/linear_regression.md
        - LogisticRegression: reference/predictors/logistic_regression.md
        - XGBoostClassifier: reference/predictors/xgboost_classifier.md
        - XGBoostRegressor: reference/predictors/xgboost_regressor.md
      - getml.sqlite3:
        - reference/sqlite3/index.md

    - Command Line:
      # - reference/cli/index.md
      - Engine CLI: reference/cli/engine.md

  - Examples:
    - examples/index.md
    - FastAPI: examples/fastapi/fastapi.md

  - About:
    - Company: about/company.md
    - Imprint: about/imprint.md
    - Privacy: https://getml.notion.site/Privacy-Notice-ce7fa0997ed94701a51cbb7dc1d0314a
