site_name: GetML Documentation

plugins:
  - search
  - autorefs
  - mkdocstrings


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: material