site_name: My Docs

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
- attr_list
- tables
- toc:
    permalink: true
    title: Page contents
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra

- pymdownx.tabbed:
    alternate_style: true



plugins:
- search
- autorefs

- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
          extensions:
            - docs/plugins/griffe_doclinks.py
        import:
          - https://docs.python.org/3/objects.inv


#plugins:
#  - search
#  - autorefs
##  - gen-files:
##      scripts:
##        - gen_pages.py
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            members: true
##            show_source: true
##            show_signature_annotations: true
##            show_type_annotations: true
##          options:
##            members_order: source
##            separate_signature: true
##            filters: [ "!^_" ]
##            docstring_options:
##              ignore_init_summary: true
##            merge_init_into_class: true
##            show_signature_annotations: true
##            signature_crossrefs: true
##            extensions:
##              - docs/plugins/griffe_doclinks.py
##          import:
##            - https://docs.python.org/3/objects.inv
#
##  - mkdocstrings:
##      handlers:
##        python:
##          paths: [reference]
##          selection:
##            docstring_style: sphinx

#theme: readthedocs
theme:
  name: 'readthedocs'
