site_name: GetML Documentation

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/css/custom.css

theme: material